// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"context"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /.well-known/openid-protected-resource)
	GetWellKnownOpenidProtectedResource(w http.ResponseWriter, r *http.Request)
	// List regions
	// (GET /api/v1/organizations/{organizationID}/regions)
	GetApiV1OrganizationsOrganizationIDRegions(w http.ResponseWriter, r *http.Request, organizationID OrganizationIDParameter)
	// List flavors
	// (GET /api/v1/organizations/{organizationID}/regions/{regionID}/flavors)
	GetApiV1OrganizationsOrganizationIDRegionsRegionIDFlavors(w http.ResponseWriter, r *http.Request, organizationID OrganizationIDParameter, regionID RegionIDParameter)
	// List images
	// (GET /api/v1/organizations/{organizationID}/regions/{regionID}/images)
	GetApiV1OrganizationsOrganizationIDRegionsRegionIDImages(w http.ResponseWriter, r *http.Request, organizationID OrganizationIDParameter, regionID RegionIDParameter)
	// List instances
	// (GET /api/v2/instances)
	GetApiV2Instances(w http.ResponseWriter, r *http.Request, params GetApiV2InstancesParams)
	// Create instance
	// (POST /api/v2/instances)
	PostApiV2Instances(w http.ResponseWriter, r *http.Request)
	// Delete instance
	// (DELETE /api/v2/instances/{instanceID})
	DeleteApiV2InstancesInstanceID(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter)
	// Get instance
	// (GET /api/v2/instances/{instanceID})
	GetApiV2InstancesInstanceID(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter)
	// Update instance
	// (PUT /api/v2/instances/{instanceID})
	PutApiV2InstancesInstanceID(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter)
	// Get instance console output
	// (GET /api/v2/instances/{instanceID}/consoleoutput)
	GetApiV2InstancesInstanceIDConsoleoutput(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter, params GetApiV2InstancesInstanceIDConsoleoutputParams)
	// Get instance console VNC
	// (GET /api/v2/instances/{instanceID}/consolesession)
	GetApiV2InstancesInstanceIDConsolesession(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter)
	// Reboot instance
	// (POST /api/v2/instances/{instanceID}/reboot)
	PostApiV2InstancesInstanceIDReboot(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter, params PostApiV2InstancesInstanceIDRebootParams)
	// Snapshot instance
	// (POST /api/v2/instances/{instanceID}/snapshot)
	PostApiV2InstancesInstanceIDSnapshot(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter)
	// Get instance SSH key
	// (GET /api/v2/instances/{instanceID}/sshkey)
	GetApiV2InstancesInstanceIDSshkey(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter)
	// Start instance
	// (POST /api/v2/instances/{instanceID}/start)
	PostApiV2InstancesInstanceIDStart(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter)
	// Stop instance
	// (POST /api/v2/instances/{instanceID}/stop)
	PostApiV2InstancesInstanceIDStop(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter)
	// Get the deployed service version
	// (GET /api/v2/version)
	GetApiV2Version(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /.well-known/openid-protected-resource)
func (_ Unimplemented) GetWellKnownOpenidProtectedResource(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List regions
// (GET /api/v1/organizations/{organizationID}/regions)
func (_ Unimplemented) GetApiV1OrganizationsOrganizationIDRegions(w http.ResponseWriter, r *http.Request, organizationID OrganizationIDParameter) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List flavors
// (GET /api/v1/organizations/{organizationID}/regions/{regionID}/flavors)
func (_ Unimplemented) GetApiV1OrganizationsOrganizationIDRegionsRegionIDFlavors(w http.ResponseWriter, r *http.Request, organizationID OrganizationIDParameter, regionID RegionIDParameter) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List images
// (GET /api/v1/organizations/{organizationID}/regions/{regionID}/images)
func (_ Unimplemented) GetApiV1OrganizationsOrganizationIDRegionsRegionIDImages(w http.ResponseWriter, r *http.Request, organizationID OrganizationIDParameter, regionID RegionIDParameter) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List instances
// (GET /api/v2/instances)
func (_ Unimplemented) GetApiV2Instances(w http.ResponseWriter, r *http.Request, params GetApiV2InstancesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create instance
// (POST /api/v2/instances)
func (_ Unimplemented) PostApiV2Instances(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete instance
// (DELETE /api/v2/instances/{instanceID})
func (_ Unimplemented) DeleteApiV2InstancesInstanceID(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get instance
// (GET /api/v2/instances/{instanceID})
func (_ Unimplemented) GetApiV2InstancesInstanceID(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update instance
// (PUT /api/v2/instances/{instanceID})
func (_ Unimplemented) PutApiV2InstancesInstanceID(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get instance console output
// (GET /api/v2/instances/{instanceID}/consoleoutput)
func (_ Unimplemented) GetApiV2InstancesInstanceIDConsoleoutput(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter, params GetApiV2InstancesInstanceIDConsoleoutputParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get instance console VNC
// (GET /api/v2/instances/{instanceID}/consolesession)
func (_ Unimplemented) GetApiV2InstancesInstanceIDConsolesession(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reboot instance
// (POST /api/v2/instances/{instanceID}/reboot)
func (_ Unimplemented) PostApiV2InstancesInstanceIDReboot(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter, params PostApiV2InstancesInstanceIDRebootParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Snapshot instance
// (POST /api/v2/instances/{instanceID}/snapshot)
func (_ Unimplemented) PostApiV2InstancesInstanceIDSnapshot(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get instance SSH key
// (GET /api/v2/instances/{instanceID}/sshkey)
func (_ Unimplemented) GetApiV2InstancesInstanceIDSshkey(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Start instance
// (POST /api/v2/instances/{instanceID}/start)
func (_ Unimplemented) PostApiV2InstancesInstanceIDStart(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stop instance
// (POST /api/v2/instances/{instanceID}/stop)
func (_ Unimplemented) PostApiV2InstancesInstanceIDStop(w http.ResponseWriter, r *http.Request, instanceID InstanceIDParameter) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the deployed service version
// (GET /api/v2/version)
func (_ Unimplemented) GetApiV2Version(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetWellKnownOpenidProtectedResource operation middleware
func (siw *ServerInterfaceWrapper) GetWellKnownOpenidProtectedResource(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWellKnownOpenidProtectedResource(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1OrganizationsOrganizationIDRegions operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1OrganizationsOrganizationIDRegions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParameter

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", chi.URLParam(r, "organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "organizationID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2AuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1OrganizationsOrganizationIDRegions(w, r, organizationID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1OrganizationsOrganizationIDRegionsRegionIDFlavors operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1OrganizationsOrganizationIDRegionsRegionIDFlavors(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParameter

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", chi.URLParam(r, "organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "organizationID", Err: err})
		return
	}

	// ------------- Path parameter "regionID" -------------
	var regionID RegionIDParameter

	err = runtime.BindStyledParameterWithOptions("simple", "regionID", chi.URLParam(r, "regionID"), &regionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "regionID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2AuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1OrganizationsOrganizationIDRegionsRegionIDFlavors(w, r, organizationID, regionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1OrganizationsOrganizationIDRegionsRegionIDImages operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1OrganizationsOrganizationIDRegionsRegionIDImages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "organizationID" -------------
	var organizationID OrganizationIDParameter

	err = runtime.BindStyledParameterWithOptions("simple", "organizationID", chi.URLParam(r, "organizationID"), &organizationID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "organizationID", Err: err})
		return
	}

	// ------------- Path parameter "regionID" -------------
	var regionID RegionIDParameter

	err = runtime.BindStyledParameterWithOptions("simple", "regionID", chi.URLParam(r, "regionID"), &regionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "regionID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2AuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1OrganizationsOrganizationIDRegionsRegionIDImages(w, r, organizationID, regionID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV2Instances operation middleware
func (siw *ServerInterfaceWrapper) GetApiV2Instances(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2AuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV2InstancesParams

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", r.URL.Query(), &params.Tag)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	// ------------- Optional query parameter "organizationID" -------------

	err = runtime.BindQueryParameter("form", true, false, "organizationID", r.URL.Query(), &params.OrganizationID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "organizationID", Err: err})
		return
	}

	// ------------- Optional query parameter "projectID" -------------

	err = runtime.BindQueryParameter("form", true, false, "projectID", r.URL.Query(), &params.ProjectID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectID", Err: err})
		return
	}

	// ------------- Optional query parameter "regionID" -------------

	err = runtime.BindQueryParameter("form", true, false, "regionID", r.URL.Query(), &params.RegionID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "regionID", Err: err})
		return
	}

	// ------------- Optional query parameter "networkID" -------------

	err = runtime.BindQueryParameter("form", true, false, "networkID", r.URL.Query(), &params.NetworkID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "networkID", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV2Instances(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV2Instances operation middleware
func (siw *ServerInterfaceWrapper) PostApiV2Instances(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2AuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV2Instances(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiV2InstancesInstanceID operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV2InstancesInstanceID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instanceID" -------------
	var instanceID InstanceIDParameter

	err = runtime.BindStyledParameterWithOptions("simple", "instanceID", chi.URLParam(r, "instanceID"), &instanceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instanceID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2AuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiV2InstancesInstanceID(w, r, instanceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV2InstancesInstanceID operation middleware
func (siw *ServerInterfaceWrapper) GetApiV2InstancesInstanceID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instanceID" -------------
	var instanceID InstanceIDParameter

	err = runtime.BindStyledParameterWithOptions("simple", "instanceID", chi.URLParam(r, "instanceID"), &instanceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instanceID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2AuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV2InstancesInstanceID(w, r, instanceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutApiV2InstancesInstanceID operation middleware
func (siw *ServerInterfaceWrapper) PutApiV2InstancesInstanceID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instanceID" -------------
	var instanceID InstanceIDParameter

	err = runtime.BindStyledParameterWithOptions("simple", "instanceID", chi.URLParam(r, "instanceID"), &instanceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instanceID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2AuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutApiV2InstancesInstanceID(w, r, instanceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV2InstancesInstanceIDConsoleoutput operation middleware
func (siw *ServerInterfaceWrapper) GetApiV2InstancesInstanceIDConsoleoutput(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instanceID" -------------
	var instanceID InstanceIDParameter

	err = runtime.BindStyledParameterWithOptions("simple", "instanceID", chi.URLParam(r, "instanceID"), &instanceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instanceID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2AuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV2InstancesInstanceIDConsoleoutputParams

	// ------------- Optional query parameter "length" -------------

	err = runtime.BindQueryParameter("form", true, false, "length", r.URL.Query(), &params.Length)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "length", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV2InstancesInstanceIDConsoleoutput(w, r, instanceID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV2InstancesInstanceIDConsolesession operation middleware
func (siw *ServerInterfaceWrapper) GetApiV2InstancesInstanceIDConsolesession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instanceID" -------------
	var instanceID InstanceIDParameter

	err = runtime.BindStyledParameterWithOptions("simple", "instanceID", chi.URLParam(r, "instanceID"), &instanceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instanceID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2AuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV2InstancesInstanceIDConsolesession(w, r, instanceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV2InstancesInstanceIDReboot operation middleware
func (siw *ServerInterfaceWrapper) PostApiV2InstancesInstanceIDReboot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instanceID" -------------
	var instanceID InstanceIDParameter

	err = runtime.BindStyledParameterWithOptions("simple", "instanceID", chi.URLParam(r, "instanceID"), &instanceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instanceID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2AuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PostApiV2InstancesInstanceIDRebootParams

	// ------------- Optional query parameter "hard" -------------

	err = runtime.BindQueryParameter("form", true, false, "hard", r.URL.Query(), &params.Hard)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hard", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV2InstancesInstanceIDReboot(w, r, instanceID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV2InstancesInstanceIDSnapshot operation middleware
func (siw *ServerInterfaceWrapper) PostApiV2InstancesInstanceIDSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instanceID" -------------
	var instanceID InstanceIDParameter

	err = runtime.BindStyledParameterWithOptions("simple", "instanceID", chi.URLParam(r, "instanceID"), &instanceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instanceID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2AuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV2InstancesInstanceIDSnapshot(w, r, instanceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV2InstancesInstanceIDSshkey operation middleware
func (siw *ServerInterfaceWrapper) GetApiV2InstancesInstanceIDSshkey(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instanceID" -------------
	var instanceID InstanceIDParameter

	err = runtime.BindStyledParameterWithOptions("simple", "instanceID", chi.URLParam(r, "instanceID"), &instanceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instanceID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2AuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV2InstancesInstanceIDSshkey(w, r, instanceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV2InstancesInstanceIDStart operation middleware
func (siw *ServerInterfaceWrapper) PostApiV2InstancesInstanceIDStart(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instanceID" -------------
	var instanceID InstanceIDParameter

	err = runtime.BindStyledParameterWithOptions("simple", "instanceID", chi.URLParam(r, "instanceID"), &instanceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instanceID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2AuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV2InstancesInstanceIDStart(w, r, instanceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV2InstancesInstanceIDStop operation middleware
func (siw *ServerInterfaceWrapper) PostApiV2InstancesInstanceIDStop(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "instanceID" -------------
	var instanceID InstanceIDParameter

	err = runtime.BindStyledParameterWithOptions("simple", "instanceID", chi.URLParam(r, "instanceID"), &instanceID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "instanceID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2AuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV2InstancesInstanceIDStop(w, r, instanceID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV2Version operation middleware
func (siw *ServerInterfaceWrapper) GetApiV2Version(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, Oauth2AuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV2Version(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/.well-known/openid-protected-resource", wrapper.GetWellKnownOpenidProtectedResource)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/organizations/{organizationID}/regions", wrapper.GetApiV1OrganizationsOrganizationIDRegions)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/organizations/{organizationID}/regions/{regionID}/flavors", wrapper.GetApiV1OrganizationsOrganizationIDRegionsRegionIDFlavors)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/organizations/{organizationID}/regions/{regionID}/images", wrapper.GetApiV1OrganizationsOrganizationIDRegionsRegionIDImages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v2/instances", wrapper.GetApiV2Instances)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v2/instances", wrapper.PostApiV2Instances)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v2/instances/{instanceID}", wrapper.DeleteApiV2InstancesInstanceID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v2/instances/{instanceID}", wrapper.GetApiV2InstancesInstanceID)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v2/instances/{instanceID}", wrapper.PutApiV2InstancesInstanceID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v2/instances/{instanceID}/consoleoutput", wrapper.GetApiV2InstancesInstanceIDConsoleoutput)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v2/instances/{instanceID}/consolesession", wrapper.GetApiV2InstancesInstanceIDConsolesession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v2/instances/{instanceID}/reboot", wrapper.PostApiV2InstancesInstanceIDReboot)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v2/instances/{instanceID}/snapshot", wrapper.PostApiV2InstancesInstanceIDSnapshot)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v2/instances/{instanceID}/sshkey", wrapper.GetApiV2InstancesInstanceIDSshkey)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v2/instances/{instanceID}/start", wrapper.PostApiV2InstancesInstanceIDStart)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v2/instances/{instanceID}/stop", wrapper.PostApiV2InstancesInstanceIDStop)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v2/version", wrapper.GetApiV2Version)
	})

	return r
}
