// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/unikorn-cloud/core/pkg/openapi"
	externalRef1 "github.com/unikorn-cloud/region/pkg/openapi"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9CXPbttboX8Hwu3fazhVlUpslz3Tuc+wseo0T10u6yc8DkZCEmgJYArSjZPx++zdY",
	"uIqUSEl2k1S9d9pExHo2HJwNnw2Hzn1KEOHMOPps+DCAc8RRIP/meCHjKBienkc/i19dxJwA+xxTYhwZ",
	"VzMEdDswPG0aDQOLn33IZ0bDIHCOjKNkIKNhBOivEAfINY54EKKGwZwZmkMx8L8CNDGOjP85SNZ0oL6y",
	"g7twjAKCOGLv4Bwl63l8bBgzGLgXaEwpX7HOX2aIz1AA+AyBQDYGmAHRNV7zXyEKFsmixTcjvT6+8MXv",
	"Y0o9BImcGhPGIXHQWhBFDcthlAz1JEDyEJny2ZpVimkR48gFNOR+yIHqVQYh9bUIRphwNNUzz6Ezw2Q9",
	"iHS7cgjFAz0JgAjiDzS4G57+LDa5Yq3HnkcfGAgQo2HgIAY4BWMEJtjjKEAuGC+AHqsMbvFUGdBhjuYs",
	"BUPGA0ymxmMj+gEGAVzItdJgCgn+BMWK1sI13bgcuNkhnwTC2Sl2AOb0gGWwXtrXRgD3A/oncvhaWOt2",
	"5WCOB3oSCMej7wC4eqwyuKY3shFIAzStQr2qWTlAo2GeBJ7R4DsApxqqDJqpXWwEzJDgOxoQ0/Fo6N46",
	"NEC3c4jJrX83vaU+ItDHtw6dzym55XB6iTzkcBqs2hFgiAM6ARxO5XbmkDszAKdQnFOpnWIij9QJDeZg",
	"JLfz4z30QjQyGiPCZyEDDzNEACIOdZELFjQEU8TByPgvh9MfJ5T+u33qQD4KLavVEz+NYfDv9qlLpyOj",
	"DFocTjcD1KMiEsT4C+pilFZyPrROAgQ5ulDf5RdKOCLyj9D3PexIIXLwJxMQ+mygj3Due0j8cY44dCGX",
	"i4kOq4WpRxbrYD5y5Ect+V2hR1jdwbiNeuYAoq7ZaY0PzUFn3DEnndZkfAh7Y4iQkZOaop/b6VmW20Mm",
	"GvS6Zmfc6Ziwb/XNfmcybk1gu3dotYyG4VPqMePoj8/GxIP3NJB9ncNur49arjkZwLHZ6bZdcwDb0Oza",
	"7cPu5LDfafXGAuhzOEWyA7Qt1LZQ37SsHjQ7fdQzYds5NNvOoGP3+gN70rZTQoFSz7QlK0p4MePIfrxJ",
	"5JJcAkQte+AemrYltt2zbLPvtBwToUNk9XrjQdtBkqarsW8OfQrJeVqOFFRHtBHiRFNBc0lqPDYSgrj2",
	"3ScniC8HSxuAXAFoNchD2WY1wCXmTujcDzk6Uf12BfUCkGtZW4MFBct6FLrnMbKgEPjIPXbdADF2DnGg",
	"fnewGxhHhm01+02raR3YPUPQ/wQH6AF6nmzj4gA5Gk6YTMUAkl0Dbhz1LcEsaII/CuH0h2EPWk2712/a",
	"Teug1TEUK3HqUE+IQcc3HhurB7StXk/9+Qx+NI7swWCQm8Fqyv8d9I2GYR+K6dTKW0Wz3cTqvIDkhiQr",
	"ujJ9BMmTBzMeUOPICMch4aHRMO5RwNR+Wp2m1dFncUSs7ceYlF00gaHHxXbDsYed4bk4ihWFSOIgcOzF",
	"pFaLyDPk+EuAiwldU21M7prOQXKRLiR5dI8lxjYj8+geJBHowkHLGnRb5rg1cczO2B2Y0Br3zG6nc3gI",
	"W47V6naMhnFot51Jt9s3O267ZXa6g77Zh5OWEBbd/uG4dwi7lnFTGTzRBkoBEysQerVSiZC9wCSgcwAj",
	"kBXCJ7oM7/xMnlHG08LgOaRu/TNfdxFKjOQVJwwwX7wOaOgrnLvdQbcDJ6btHtpmB44n5nhs98zuYWvg",
	"HNq9dr/fk8jcWHl4ugM7i9qSw0NzVWw1qXRwR613fm7/fUSzLQXUR8vKMz2PlrWHu5TbzKeE5ZTtt5jx",
	"C/2lDor+yOIooosrLHHVslpt0zo02/aVbR11uked7u9Gw5gh6PHZJYc8ZMaR/qu4T+AaKFxW456RvWSX",
	"eywORUym8U7iH5H7xSiVaykXWq592LPN7rjfNjuuDU3YcW2zc4h6XeSM0bjflbIrq502DKZ3vdEtKgHJ",
	"mqtKWjscd+2+0+uYvX63Z3bc3qEJDwcDs213xrDX6/c6g4nxKDrV1JsvEHQFA6zWnCPGaRrpS8kmTLPn",
	"mT3PfFk8sxHL1GGXjPZ+ijjE3tfIOV882+ziMr2/HX8pt+O0wFjGU3STS0vJ0+q7K+ULoV5nXXxSyEh2",
	"6XXGk7HVssz+Yds2O3a/ZcKO0zcnfdQdOxPHdtoolsBiMa1efwx7/Yk56A0sszOYWGa/Y3XM7qRjj8eH",
	"Ttt12pLG8T3kaHiurDXif3YV0k9AKTpGBCEYLYKccRESIs3PNwWI2NTkljOOlQlDV0o65ILUB2nFjz0p",
	"BeJxLxj3gnEvGPeC8VsWjDk7bYEUZF+lOWIvB/dycC8Hv105eLOZIGTFUtDDTPpkctKQSXEYWXW/UguT",
	"NNJ/sWLw2V0GCRXqYKiNXQhbW5EeUCDAg1Kkn+MvLaatZjvHP/12s9NtCgneaxlPaWhKiL/UzpRzfmR4",
	"hn2tvow91+y5ZguXRor+y/gmOnPy/KMOnRqBi9BxkM+Rm2a10hB2MIMMjBEiIOoGIHHBA/Y8GZkZehPs",
	"eeJXtiDOLKCEhsxbNEfkNxqCOVwAn3qetpuoWEc5wJwSzGkAMGcgTcnyo2JGoBA/IpwC+AAxl1v3UNoW",
	"Q30U6LDlekAYQ1c7tjc7plEQCK3RwOQeeti91eAyGurLbRagETDH1F0A3cWoLFNrbEstq4B+LtIrmCjb",
	"lhofyNXIjTYAjRI7VGuXIgYIFZAnHGIyIjBGpvJPgwlGnlubBh1KJh52tgR+NEoJ1GFCcg+Yz+S6GZwj",
	"IMQ2gF6AoLsA6CNmnD03NvS6oh0wtUJIKJ+hoAFCFkLPWwA+wwzMESRMrH4BZvAeZfdRF/ITGoyx6yKy",
	"HejjYUpgHzIVJuoiwjH0GHCpJKR4AzEBCVGMPTRF7O/hiAfIgIsIVuHlMOQzGugTvKHhDxdC1jkwZKqR",
	"WH+moZBRd4hEOxRyLLNH5lBfxnYDSMDx+TBmNAkmwWXkuwQ2I0KQgxiDwSIFHUBVhLiUli4KgO9BPqHB",
	"vC4FYMJRQKB3iYJ7FLwU8NmOFpgcSEO6mBy0xOEUKEA5HsTz58X3MQEhQR995Mi8rACEZAaJK5Yl+wDq",
	"OGEQILcJrlJYh4AHkDCMCNftIHFHRHxloeMgMRYBQtTwYNEEYDhRRIMlSgXCHMhQA/gegkyQhE8DDjAH",
	"kAliwIyFtXmYUP6KhsTdDm2E8tuJGKYEZzyTyBaL0vhMkILzeXF4Le0ogowmmLggEfB1IRiSiH/RllAU",
	"ahFjt0qClB1EIZ8JOahG08fvM1N/0RIiKaT2oFlTKHzooy/kVgFUlQ68PL+WAQ4ljHrovcx63AywuqW4",
	"zbzFJPwItBUOdJt2t2mZttXvmXf3c/D9OMSe6/4fz1lYLRPO3V7HtLrtH8D3U8cB319LKx6w7WZH9FJG",
	"Pfv/t1pNq/OD/rkBXr+7Bp4Lvhf/fYFJyLHHpKBW3X8ArWa7/wP4n4Ft6gEvz87BGSXgOJyCDrD7Rx37",
	"qHMIrq9OQMtqdeOJU8ttDmy5YvmT3e/+MCIndD4Xqq6HCToCL96/v7odnh2/fvnjwZhSfnA/9zAJP5n5",
	"PQeU8h/Pjy+urq+Hpz/aPTjowknb7E66h2an3bJN2IMT07WsnuM440PX6oCAAo2VHzlf2Om/XFrAhwQ7",
	"P5r2ptRYhx7K7AGySZQpmwk/2WSuS8SYjAjfhPjCwDOOjBnnPjs6iGyBzalH7aaL7puEOdBDTYfOj3pW",
	"3zq4J86thzlqzvjc+68P+ezHf7dfST76d/vU6XXQpD9GZgtJC6ndMftt2Dd79mGr3+t1xoeH1tPCXcNi",
	"NeCZarQF5JV54QlsN/bg0DIt27TsK8s6kv//PTLRDGDf6bUPLbNj9bpmx+1Ac+BCyzzsHfbdScdy3IGb",
	"mGimzU5zhqezOZo3oW1ZTXvatK3pOG0lgYEzwxw5PAxEl4/93m2vYzQMxw9fwTn2FsaRMSQceeBXRAk4",
	"9yDHJJyDvt2zrsD3l3cLD96hH1QPZhx1GoaL2Z1x1LIaxtQPxRwenWIHeic0FMBpNYw5mtNgYRz1Og1j",
	"Tl3kyUkYx8Th4GzY6lpGw/BnC5bqZjeMe0Rcef4cn52KPUTDtFs1rA6bIHm1cUI3qk9C0t70ZNa/ltlq",
	"XdmtI6tzZLdjCoK9zmTQ6g3Mdg9ZZqdtt8xx37XNbssdtN1ubzA+TBn5wnHYalkd895utrrNnjn1Q7Pb",
	"6jb73abVNQ8d5HbsbqcKPWlScAN8jwQK41EMTQLSQHZsWwL1b/R/WpZl3KTw/u7D8HR4LKajKiKcuihK",
	"i6djDxmNAofWJCJjF40xFHe3OxQQSXPivPloNIx7GGAowK7V+iI3WMNg+BN6jV8YR7bVMBid8AcYoA+q",
	"nVxOkg1sHBkaZKLjPQ54CD19bxLfoh+0RhQb+5g22slbuvFUVK3objVRqzaAzyAHMEDSDAU5Fpqotitg",
	"tuo2tmYJ6vPzWb7z2+TUBww5AeJADOQgcT8EjM7RwwwFKMpMvv5px1bz8M58QIybdl1jNoKCo1SdFS0Y",
	"3ynLMItzWHTCsgA149C5ezIC0thbTUG6UX3aYGz2E1pspstoG/dPSDC8Kf558fL18B14f/7y3eXlG3B+",
	"MfxwfPUS/PTyN/l1RMbtF96YvPsET+zg91/vuPvny2Pxz4vX3fvx/Fr88eV4Pgh///k4+ueF+NfZg/g3",
	"/zQiTmvKf//l58W7q+uP70WrkxN+f9F98Qof/9r7z/Vrev5wEL4+uLZP4X/wO9t79+a3Xz7d9X+bnb9H",
	"1w/HxyNy/NPx7NPJh/87dB68y5/VuHVGHZGicY9fnni//fnb9OOrP1+edf6atZl3OLxsuf6LT5cf7y6u",
	"rHdXi8Hw7WKK4fGI8L9agzd3L38ZvpgE3Z/h9OD0P53x4Or6XdAbtn+5ttzZ+P3VR/yy3+1eiRW++fVD",
	"CH/h9868M/391xd0RH7/xfac+Ss2fP3h7uzPa/vs6m4KWx+6IyJB/fLdaSkankgjVJRUYhgR67hDi2bK",
	"0SfZazk9t6RmA5iHHse+h8DZ8cnB8BxA1QV8H0AyRT8AH+JApi76UNw0ZwENp1pyaq8O8GnAmyNytfAF",
	"R3uLxHwmKx/wVGkbzCLLP5lKQwoIaKhzIP1AfOJRVQKZSFzk4DgZnl6IBck9io5LRQ/m0NE7Lx7h7Pgk",
	"3ueKgR7T2Vx/qBXdJBJq/CdypBllGdgyt6WgpEQkVnSPeBESyLLYQ1TIYRX5FCB3qdJDvKpLaWbRbRFb",
	"taoYnzq8Jzk4o/VyCpCMD1IprNKeLam0OSIvFkAHcTQAJd4C+NC5Q3yp6XcJ4UiD5gQ66DsGEtIbkfyU",
	"8lwTI0RlhQC4Zki5kiRFSdMIVDVIkpmUA8rhaUKTBz8NObh8d3wFgtBDWbgvcVi0jsgFFmFMwqiQ+vKI",
	"yBdoKMDAqvIMWbZIaw07Mj1FprizaOjUkV2j8MSl6JLnmXi5esgi9ikaR4mw9xOpKVVahJq+8TkHr5Tn",
	"uUgSRJQ4PJWCgHPoKHfTUqYnp4XIzscNrK0/JSRppB5lvauYFM6QijBYVXCp5rg5POW2kZ41nb+9jL6b",
	"CrVGBObxRCs8qbUUkID0ohcxSD569Rn4QoPg0qG+tDVLaIoFbswomkZTd6Vq3VTzdbwVj3uzDsLrjidn",
	"KTqu4smUy1ZbIQsjLi8jniWayaJbZ+atXo1opBKtl2Cn+q8E1GWMpNI1yhbLi6shc1K1IzEDgQpzAbRE",
	"ElTftFr8W+3nSeJfVhYYK1tOFQEST5EWF40qcNb59ivgvJxk/+WfiZufhpkw1jOlN5fRYr74SqRml1Fm",
	"EpKcH0lPBKIWhQSYNSLsHNhv0sM/pqOey1YbtShcLXbLO5ZsMA6SLusnG5T1TsWmlfXXTVLabtmZv2RV",
	"2Tm4z5cneUyH0ZXuQbZYtwW2wbLXmfy0LvYWT5CzcDx0PoMMLXEZdtMR8wlSGwn5x8srBHWO0CtzKSs/",
	"MkrizpPaQAnHVjtoV0iJomN3OUlorSwJEHS/Mj0rs8uayla2bzWNaz1lFKs5eVDHmnK2aFYW8pUO8aVb",
	"QHycF6sUuRSWWhXBMl1X6APZOSrArOJhV3bIMTY7T1lQ88NcXr6JxfAdWmgjh7IdxPEUadg9KeBSlLYG",
	"LOluRSImD55ohUDoYAWMnKRhrVq6biYnjdOmdsb6ibPpLRwj7wP0wmV5rsV4tOCbWpCqSkwZaJWSVpLf",
	"tYF4Zol8fhYwplOp8tt/F87HKEhXp0tRebp2eQEi4lHrYaLWuZhBx6bHYoZj1p6KRWy58Yq3O88LCHj9",
	"8mUdwmpHDZJRlPJW9WXfpgoO9K2P5DpY3RSBpeYP1WoYZbEWPJMgLxicgpDpuOPIwm40DEqQNonm9N2b",
	"x0b2tzg99kZXH04hGLurpi6526TzbVfmw4hBovLaxcdatnJmeeHtKnUzC8WzrAta6VgbnhZah1LjFNFT",
	"lI19EXqF64++S/cCkM5e5ciA6w7lVCZ2EYbiz2lvDQ/gZIIdOb7veyrIXc6sTNaIhHNJJnFmt3LhpLaW",
	"NjEFvMTOTAMeO8tkGDzjMFDeLPVROgyLjpFU/njRyIi4+VEaABOBZXyfeHlUsAYNeAPgSWQfRG7JhHGG",
	"+gpeH55epHxd8dYwB3M8nXEZRE4WYHh+3xH7HZ7f9wAmqh+hPHl1oWL19XQ6fIkpX37N+CQj9HHHNxpG",
	"6PoFeMuRb0JFqRk1blOgWUfaK4GXoXG2hsgrSdAMVxXALitZCsWGkJNajEXyqojHVHDVDg0TlJ2qQR9T",
	"YViFnqDY980WjKM50K0LRW4cvVVtJB1srY6O9QZbDYZkmiJyyJWqXeGYWVmo9otVMLL721jBKBimsgMz",
	"6rv3X34x/sulPPcVKH+XyZ5eN1Qq9kFmEOJpGJR4uMrDNyqEhuR7rbTrRg+D0UBmB2UQARNrbwoM8QNg",
	"y/nhq5eXaZ1SvkrBu84fnMbR12OozPF8RRNl3GsH7uDMCjaCb1KZoIir1Vdwcn59cHF8ptS7FXyV98Cs",
	"vKFUHyxb2qAKbFPs/NiQubCnmoby12qZVs3AGDLU65jR6z4ZpgaYTGgwV38WCrMcgEW3u9CnBHgwJM6s",
	"OSJX+g0hyKMUeYFMgBmY0nsUkCSBVVKqiQnmQgUnLgzchkrNjxIf1USNEYHgbHj2Usf4CW1dRrbfowZA",
	"3BEgUzMKll5wtFbKxjhP8LSSuEqMKIJlVIiYotAMnOCYhrwEwRsdjeICraQOmAqxA8bIo0S+6VTiZU8K",
	"TzyD82ql21AdkHmXYUQgiWFgeROl0l4OmffgVRixkvuhHqyrhBCsoq8VkQPr6/R/8Trp1tooKzs8VxQk",
	"qXhXyxYLWr6rlT0pV7CYn+KmqioCOAuZunqr+hbg9N1lVMVCxcZ4CyCUnEDmZwNnBgPocBSwBiDSqs2E",
	"rJ0t/BkirKGtFEI8Iln+hM+EcIk6SaVH9lIiVMzLwZwyDnrt1Nji3p88BTqHH9+qlz+Peu2GMcck+qtd",
	"HI2csjWtwEfy/idrCHZkSAbfBoiHUv7jrEuvwMScHzn7ougck6FqaVcIW017fiq4m6Kpig1bhc9F1Y1y",
	"jsKZVG7e6t731AvnKG3SqGN/kBpzuYbzSmk3MVRXYT+uWFjBeqzswo9lxQhXhn0t99iBA2iVCnStv0TM",
	"uTNdqLZaEu+ysaShFApIFSJXRNRrzLNfhc5bGDAlFSI4R9FBL/cHwDCS/KouFCYzFGCusztEc98LmTjV",
	"ZzTggIWTspj3bTXtckKVK4+JNT6q1IucWFJeXcr9Zyrvee9to6o6nwqjXXF4beix1bxYZCtPBbJuwKs1",
	"+KBY3a1NkDOoS6vsyJW+FMlbFfpaM0B1sVDuai4+j/KLSV0r4naAIc4xmRYEU8S1dfMjvVTFYoqGKzJC",
	"5UAbDVsE0iL70wqo5i4zw9PV2tZS80rpQbWLxCzN/BoRFGBHVzmaI8bgFDWWsp0pDPmsVYCH4lGPgVB8",
	"kR5VrR+gjz4krtLDJQO9ubo6102EEG0CWZaKScVViFc3avj+OOQz0GparWxsfwOMQ5VkpsZGWkkXawww",
	"4jCIzQRiAlXj5fh8yICsuCbYTkxAGUp8gkLYJvNlnaD5qn+5Glj5qkDpWkupqnVzxGfUvRVftZ5qCEyy",
	"0PdpwJF7O0cuhrcS1/GTy7eIcMwXt5zSWw8GUyT7+AGVNcPGHrqNcoQbqTJtRW7aglpFefR9QMFYAEWT",
	"g34PYxxVOJMjrL+Tl5cGK2KvbUOWCmhQ3QFTl0RPNAfyhe0G4HHKqazwJkgjdhsIEaulsgMJGKMRwcRF",
	"H5OLlDijBY1KloCco0DM+f/+sMzBsfk7ND/dfP/fo+Rv5m3z5rPV6NmPqRY//PdfRUxeAxJp18UK03Jl",
	"h9IGJoqcDTvvg6rtI8KyeOAEoyDryaljDcpNWsFzE+0gST8eL7LrktX8UhXRAgTrV8Bc7wV4ClRVpJJl",
	"5FV0v+0CZclUm2IrWs1OEFWYVlIIhFTZWn3VSsrTJWdHSO4IfSBxesBCluSYBtBN6scVSuttjIbLWRhL",
	"cJNRYp4nDsUcxFTF3wBzVKB+rTw9rtI0kPrUSGdcS8ELw+lcELXKzxaqtTy+51TWWyEcfeQr76lPHALL",
	"4XSXuTMcTgsjxuRubjbD9Xlhsk8hqybVlivTarpX+q+SZl2U+7xTIn5yoSiAgJ2LZUP75yVaV9WnVX2d",
	"IuByPEdZyafKy3qIqxiz+LLtQo5M0fwLyJD72/LEliV/7SSqaieCDDHb6hhgaH6PSgLG5pBw7MSxU1ov",
	"FKgG93az1Ww3R+Q8QGaAZBFYJVB1zJa648ga22EQIMK9BYj1/5xKeT8auf8ZjZqp/2yrNpbQ/lOqiSsY",
	"TIWVuy8WxdwlqyU/zKgOP3cznFZ4PGQrYlXnWD1BdY4ti4YOCf4rTA1ecpufU1deOdfuXHkgK+w8GnHN",
	"zmF233r4qvsuSpnMgLwCv6piyxHTYpa5fumb158h00YxZeV0KfmORww+IpAs1jwioMwDY0TQBMcB4JHl",
	"FH9C7ojES1Abb46Isd3dlMPCYC4Op2AOfV+uMxhjHsBgEV0zqbqSsiYAV9JzJ2uCE6qMEtCTteAxmY6I",
	"Kia+ADFPqgo7sl4bR9IAIpqEDAn5h4graUgFKLuyZBBWyteIaP1KRd1GkG/I7rqcmPjkQI6msmIywLyq",
	"ofQ4YgCx69IU6/via7sgUvkpMrNyOG1WNVCrMW+2RuE6457QDCsbSGtSz1oz35pgkWwByiX/xfk1SLdI",
	"K35xrUooWvQ6FXS5WpWAi5wpqSrAy2W84qLQqztWKL8VjbSeNOrV2C2MHymrsJvfn6w7XET/1xdvJV/q",
	"jFIZkpsZdP2Oxdhbb1Y5eQrTVOSXZ4mFKVXUK0XEbLDfjYNnNp2rBnzzzL2zrWcGfmwYYxggsWevPOaX",
	"J35rfYBD4CIXO1JX0aEBxZG/qeLKBXsPkNajhbBS1WszTzKj5rQJZM3cJP4mJ9KWdUI/XOuPOzm/Lolk",
	"iKJGlnvDOQ2JPBOQP0NzFEAPiNbiPvD6RfFouhTwznA39cMoGjiqCL16qaqVXCJ+UcHjKIEXD67B0cgS",
	"444YYnXiUFRoeqOTt5qw2/b4nfrhmarovbyP1+fXGbptGtsesNFs6xSW/MxPBMN48zuAYrFoFBtZU98r",
	"W229iBN0ixTrvz6/ZgDeQ+xJ9zFkgCEUX+rfXxYzchm3SWiv47G48vsKOimOz83WhS809+km+R1+78DA",
	"ZT8kOy1eWFRvfLeU8UGNmhcuerIIHCkxk91oI4vYreVNsqJCEAocqKWlVWRdgL0hK/BvrR7j4lzuY6Ii",
	"t7419UplYdbKW9lg/B1kuNSf9bWu7l9IRqrmP8A64sfzUEFxpOhhgDWDaHNjI3pvStNoLBPLzELIexpJ",
	"H8XV/j0iQwNtNzh8f1nIikvZsqkWBaWn4xcZVim2opVyeEld9gEGfHEwxpSUIPCJ844nsS6+w+G1gv+Y",
	"PDex0+F/UoOuyppOQ1w3UvB2Ebvj1D9YkbJSmkCt37vIvUWaUIecYKQezRgZ6y/qGjgxEhrVsqs3FLw1",
	"zppnu2ru+joUC+T4mZTdDv3+MvMYypKTHRM8D+fqFihaJT4pHf/L49DsVdph0QMru3sYID94wSstu4bb",
	"h+z4eUaIALq0EInFXd82Y11hVS0d9h0DXpRzp9zmaWXQRzKcMXZ/yD+ql2sa+vHLHemIq1z7ssF3rLyk",
	"3e7TERPYLSFR/rob7HxYose8HQpyIOZJ5z+leEvapNL4Sr86lLZwNQxIFjvC1Er7Rc03hZ7iho6jNKGt",
	"ruclCanFl+2YgXzRSMadkEweSoSf85ifkjfbLzmVXrPoj7tgqVj1KUCVPHzxOJSGxsh3FS0woM6d4G39",
	"tNYOFrLCCqrsnnSypGIoPyFmqQhWF01UtStx94fOnaB/7dFMLx+5M8hl6I58CGwH6/8pVu3y61d6jeTP",
	"9BrUi2Nbz6w+v0o9ClVSCCx6N0r7zmWmsXygXj2oLH2cHhb8VFAofumdqfw0w4mYJ7qMEWX71gyemlCH",
	"drCUXUYPqd4VpgQBNqOhJ5NIU2FW0qoe1ZOLyvNILzHA8/gdKKBe7GIjUjTnGDJkSkEXp+spf7rKEp3r",
	"lNnUrGJBACaL/fD2+J3MG0p7x8tSKJaAtvVhoD6XJSSrr8+alb1J2Y4Ndvw8fqjUXMvkvVRbISGwggzH",
	"FDfuGBQxo8cH186nuBLD5qGtczDine0I2ld6C2W1EL5jyYPveQGaPG6XTpXflURdqb7ED9o9hWKS4vJt",
	"tZOim1MS+nKeIdpdWVFVoODSM2syKxv4AYotf3HAYPTfiKObxrbEpV97K7rjx2+9LZ1xK6pdC4LMVbyu",
	"EsgfD1jELTq3vihbR36JdBvMUqGRsm6DyuYRB+KHM50elvIH5u48+FPBHKfxjbyy51MOtLyPVDrgpSAW",
	"nesik+Syj64vr+K9Uud0lTssdJM43wyMEQwE08tH2bMvyMvwPI8+KHLWD9nLLyfURUs/XmcetVYpGnzR",
	"JHesiUIBLPkOZyf1uvWBWv/BfesgM5I4ahzqyz0K1hRr22p0OUKmdpf8pJ4pxGRCS97u0ynslyi4xw6S",
	"OQtaTDJZfQbHoYO6JPtSeKC4iwB5GRmROSRwiuaIlBbv5Zh7KFUHOTVx5oFcu2m3mvJRb82QxpHRblrN",
	"tgrknUmMHUAfH9zbB+lkHHbwOZOqdPoYPQJTFPMUle7QOxUrnKICs+dbIa6h5yWKo7hcaldmej5ZFjii",
	"xqErs0H5sY8/2O/Ti3yfWWJcCVkwiopskottWVaZPI3b5SodJ6/fPjaMTpX+NSTyGLoXKnUyO4u901lC",
	"ErGKTKpKzdPe6TxxSmd2ks5OJyGUv6IhyWyku2O0yGcbCfQu5ZElE36T6VJiVcagFwvUP2Rd6o/mTOW4",
	"Ro//Ju9flMavJ00OsnyXVBl6bKztWi+eM6o6m5ri5rFRVRzopDZ28DlKkKstI54NLvEK01ttGD4tCk1R",
	"5U4ZgICgh3RV7qxAOqdsrUQ61zA6j+bPiCgpAl5Qd1FOxlETLCSUXNdJriK7Svh+XBJ5rboiby/xtpR4",
	"g51OEmXlf40Sb0dC5OCz/tPw9DFOdytSnuXv2Qr6WV5VLTbm1pNoGcYmbFYDIdBxkM/z1Lvnxb32sYX2",
	"saGu/hpxGTXNpbcQ3GP0EEUWlPJZBSV9Eyarrb6fylXv6XuvXT+1Frm+V3yG5XTPoqwjVfo1OcnS12P1",
	"9ANyU6UpCZwWaqbhrrjw79ZQ90fnXrR8U2rsgXzx6Su4HW8u1wrv1LGKnn8EK/f2lTaxq7Kd0o2MZQEC",
	"B3oIuPRBisIRyb1Kp+qkxWM+oAABX73itON7eyweX96rimm1ZWT0TNheLu7l4l4uxnIxYt6Dz3Fd8ccD",
	"nVpMy3K061xl0qnKakCdF5rKBn2Cy0z0SOpZtKuTzJ42uepsnua+lwF7GfBPvnat7xULn1q91BMKT+BG",
	"qSwidfGFbXyzyu0ReT1ylSL+TlEZ7+25hKWuoLGXlntpuZeWdaXl84m+GQzcAI0p/Xbv0xuioOwW/gYG",
	"LlAgS6R5ZGOET+TqLpfvbxIE7i/Be5H+VYl08XdCzbG0+zzvrZjRCd/LvTpy75JO+Bck9y4TBO7l3l7u",
	"7eVeRbnHYbAXeVVFnnofEjCVmfoFCD2Jvb2828u7vbyrKu+ovxd3VcUd9QEEgUrO/xKkHfX3wm4v7P45",
	"wq48SVeWipb5FBPscRQgN5+2G1eGl6VGXDyZoAARHke68YW/JqmMxa/IarmYLmCSSg6u7ba40Nt6ct+D",
	"XuSembdi5i+W0Vg4n8NgEeVABjFZqZec/jAiQrvZnbPgpjb3HnxWfxA/lRY9jnJOdYHtSkmfTGV9Rpms",
	"CW/qWZK6JPJlkRlkcYl5ug3fXujtvNKbeXI21vvZs/E/go0nMVlFbBwR2s1z+vwipt0Z75fVC4tYX5Ux",
	"247z0xXHno7xh2onT873ajd7tv9HsD2OiCriek1lXw7Tt1ZlYmfrSVSs2uAUVKEoZM5WKse5HjC2zl5v",
	"1IT3zyEKFpsZQOp3jfBVv6euyLbc9WajTDmFng8tgda9wNrbDnYX47SinEIVG1xrq+oIEVmr+crTK+wa",
	"LLJnj2/zPC9LaGg9ae2B1r6ewF7Mf3P1BOpqk6quwLoSAq0dlQXYS/I9B/zNwdzbFAAoTe5v7SZhP2IP",
	"Ne921aT2rLZntadTzKKq/KuskrpJTYtGPHL5YTSMJ9/bNL5Em0aMwr3s2cueXRl5Uzwf23nj327W2juy",
	"D4mUWDzSgqX26R2NvwOLRzTUnn++dQeGJs8I4SXEXXTwHnyO/ljRJrKKA1JWkXjeYTz83i6yPy6+HpbS",
	"9L6GpRpba63ScrKKqZbU1VUcZe1PhT2bPCebCPJdyyP1blfJgVTDtrJSMQtXc9CGGtoOzCt7Xtzz4u54",
	"UfPCtlrg2gpdG51xZaW6Njz69hW39tz67ZycOc54yoN0q8JX60SGruq0C5mxvnLVdpIjWuq+/tRednwb",
	"suPDu5Mn1cDXS4HSAiaruP9ZZNoMBu6FXF2VxNMLXVUkJWEAeCGfPYahx9Xzu7KcsY+CCQ3mAILoEUhw",
	"fHI+1HVJmiPyGw2BAwlgPnLwBC8ABGItwKcPKFBPwwHIAAR/hShYgHjJVczLiUy72Bce2cuwr0yGaSZb",
	"fVtZkbxaKoUYm90VPS9aXwe5QDzA6F698q+fNN1K97hUS3tynUO9zLrn0z2f7ljX0EzwN+sZZUWDnljN",
	"qFyXp46POCUc9sV09rLh65INivCf4AgvrpLz9/F3phCN6ExgffbeV4/Zc/fXxd3Ur8/cj4//GwAA//8V",
	"m6b6qDYBAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "https://raw.githubusercontent.com/unikorn-cloud/core/main/pkg/openapi/common.spec.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "https://raw.githubusercontent.com/unikorn-cloud/region/main/pkg/openapi/server.spec.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
