// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	computeids "github.com/unikorn-cloud/compute/pkg/ids"
	externalRef0 "github.com/unikorn-cloud/core/pkg/openapi"
	externalRef1 "github.com/unikorn-cloud/identity/pkg/openapi"
	externalRef2 "github.com/unikorn-cloud/region/pkg/openapi"
)

const (
	Oauth2AuthenticationScopes = "oauth2Authentication.Scopes"
)

// AllowedSourceAddresses A list of network prefixes that are allowed to egress from the server.
// By default, only packets from the server's network interface's IP address
// are allowed to enter the network.  Use of this option allows the server
// to act as a router without SNAT rules.
type AllowedSourceAddresses = []string

// InstanceCreate A compute instance creation request.
type InstanceCreate struct {
	// Metadata Metadata required for all API resource reads and writes.
	Metadata externalRef0.ResourceWriteMetadata `json:"metadata"`

	// Spec A compute instance.
	Spec InstanceCreateSpec `json:"spec"`
}

// InstanceCreateSpec defines model for instanceCreateSpec.
type InstanceCreateSpec struct {
	// FlavorId A flavor ID.
	FlavorId externalRef2.FlavorId `json:"flavorId"`

	// ImageId An image ID.
	ImageId externalRef2.ImageId `json:"imageId"`

	// NetworkId A network ID.
	NetworkId externalRef2.NetworkId `json:"networkId"`

	// Networking A compute instance's network  configuration.
	Networking *InstanceNetworking `json:"networking,omitempty"`

	// OrganizationId An organization ID.
	OrganizationId externalRef1.OrganizationId `json:"organizationId"`

	// ProjectId A project ID.
	ProjectId externalRef1.ProjectId `json:"projectId"`

	// SshCertificateAuthorityId An SSH certificate authority ID.
	SshCertificateAuthorityId *externalRef2.SshCertificateAuthorityId `json:"sshCertificateAuthorityId,omitempty"`

	// UserData Contains base64-encoded configuration information or scripts to use upon launch.
	// The format of the data is governed by the cloud-init standard, and may be a script,
	// a MIME multipart archive, etc.
	UserData *[]byte `json:"userData,omitempty"`
}

// InstanceId A compute instance ID.
type InstanceId = computeids.InstanceID

// InstanceNetworking A compute instance's network  configuration.
type InstanceNetworking struct {
	// AllowedSourceAddresses A list of network prefixes that are allowed to egress from the server.
	// By default, only packets from the server's network interface's IP address
	// are allowed to enter the network.  Use of this option allows the server
	// to act as a router without SNAT rules.
	AllowedSourceAddresses *AllowedSourceAddresses `json:"allowedSourceAddresses,omitempty"`

	// PublicIP Whether or not to provision a public IP.
	PublicIP *bool `json:"publicIP,omitempty"`

	// SecurityGroups A list of security group IDs.
	SecurityGroups *SecurityGroupIDList `json:"securityGroups,omitempty"`
}

// InstanceRead A compute instance.
type InstanceRead struct {
	// Metadata Metadata required by project scoped resource reads.
	Metadata externalRef0.ProjectScopedResourceReadMetadata `json:"metadata"`

	// Spec A compute instance.
	// Some stored desired-state changes only take effect on the backing server when that server is
	// rebuilt or recreated. Currently, changing flavorId or imageId causes the backing server to
	// be rebuilt or recreated. In those cases, backing server IP addresses are not preserved and
	// may change when the replacement server is created. Instance names are immutable; rename
	// attempts are rejected with HTTP 422.
	Spec InstanceSpec `json:"spec"`

	// Status Read only status information about a compute instance.
	Status InstanceStatus `json:"status"`
}

// InstanceSnapshotCreate A compute instance snapshot request.
type InstanceSnapshotCreate struct {
	// Metadata Metadata required for all API resource reads and writes.
	Metadata externalRef0.ResourceWriteMetadata `json:"metadata"`
}

// InstanceSpec A compute instance.
// Some stored desired-state changes only take effect on the backing server when that server is
// rebuilt or recreated. Currently, changing flavorId or imageId causes the backing server to
// be rebuilt or recreated. In those cases, backing server IP addresses are not preserved and
// may change when the replacement server is created. Instance names are immutable; rename
// attempts are rejected with HTTP 422.
type InstanceSpec struct {
	// FlavorId A flavor ID.
	FlavorId externalRef2.FlavorId `json:"flavorId"`

	// ImageId An image ID.
	ImageId externalRef2.ImageId `json:"imageId"`

	// Networking A compute instance's network  configuration.
	Networking *InstanceNetworking `json:"networking,omitempty"`

	// SshCertificateAuthorityId An SSH certificate authority ID.
	SshCertificateAuthorityId *externalRef2.SshCertificateAuthorityId `json:"sshCertificateAuthorityId,omitempty"`

	// UserData Contains base64-encoded configuration information or scripts to use upon launch.
	// The format of the data is governed by the cloud-init standard, and may be a script,
	// a MIME multipart archive, etc.
	UserData *[]byte `json:"userData,omitempty"`
}

// InstanceStatus Read only status information about a compute instance.
type InstanceStatus struct {
	// MacAddress The MAC address of the server.
	MacAddress *string `json:"macAddress,omitempty"`

	// NetworkId The network a security group belongs to.
	NetworkId string `json:"networkId"`

	// PowerState The lifecycle phase of an instance. Once provisioning_status reaches
	// provisioned, this becomes the live readiness signal: API consumers
	// should treat Running (not provisioned) as the "ready to use" state.
	// Queued and Building are observed during create — Queued for
	// baremetal servers waiting on hardware, Building for servers the
	// provider is actively bringing up.
	PowerState *externalRef2.InstanceLifecyclePhase `json:"powerState,omitempty"`

	// PrivateIP The private IP address of the server.
	PrivateIP *string `json:"privateIP,omitempty"`

	// PublicIP The public IP address of the server.
	PublicIP *string `json:"publicIP,omitempty"`

	// RegionId The region a security group belongs to.
	RegionId string `json:"regionId"`
}

// InstanceUpdate A compute instance update request.
type InstanceUpdate struct {
	// Metadata Metadata required for all API resource reads and writes.
	Metadata externalRef0.ResourceWriteMetadata `json:"metadata"`

	// Spec A compute instance.
	// Some stored desired-state changes only take effect on the backing server when that server is
	// rebuilt or recreated. Currently, changing flavorId or imageId causes the backing server to
	// be rebuilt or recreated. In those cases, backing server IP addresses are not preserved and
	// may change when the replacement server is created. Instance names are immutable; rename
	// attempts are rejected with HTTP 422.
	Spec InstanceSpec `json:"spec"`
}

// InstancesRead A list of compute instances.
type InstancesRead = []InstanceRead

// SecurityGroupIDList A list of security group IDs.
type SecurityGroupIDList = []string

// HardRebootParameter defines model for hardRebootParameter.
type HardRebootParameter = bool

// InstanceIDParameter A compute instance ID.
type InstanceIDParameter = InstanceId

// LengthParameter defines model for lengthParameter.
type LengthParameter = int

// NetworkIDQueryParameter defines model for networkIDQueryParameter.
type NetworkIDQueryParameter = []string

// OrganizationIDParameter An organization ID.
type OrganizationIDParameter = externalRef1.OrganizationId

// OrganizationIDQueryParameter defines model for organizationIDQueryParameter.
type OrganizationIDQueryParameter = []string

// ProjectIDQueryParameter defines model for projectIDQueryParameter.
type ProjectIDQueryParameter = []string

// RegionIDParameter A region ID.
type RegionIDParameter = externalRef2.RegionId

// RegionIDQueryParameter defines model for regionIDQueryParameter.
type RegionIDQueryParameter = []string

// InstanceResponse A compute instance.
type InstanceResponse = InstanceRead

// InstancesResponse A list of compute instances.
type InstancesResponse = InstancesRead

// InstanceCreateRequest A compute instance creation request.
type InstanceCreateRequest = InstanceCreate

// InstanceSnapshotRequest A compute instance snapshot request.
type InstanceSnapshotRequest = InstanceSnapshotCreate

// InstanceUpdateRequest A compute instance update request.
type InstanceUpdateRequest = InstanceUpdate

// GetApiV2InstancesParams defines parameters for GetApiV2Instances.
type GetApiV2InstancesParams struct {
	// Tag A set of tags to match against resources in the form "name=value",
	// thus when encoded you get "?tag=foo%3Dcat&tag=bar%3Ddog".
	Tag *externalRef0.TagSelectorParameter `form:"tag,omitempty" json:"tag,omitempty"`

	// OrganizationID Allows resources to be filtered by organization.
	OrganizationID *OrganizationIDQueryParameter `form:"organizationID,omitempty" json:"organizationID,omitempty"`

	// ProjectID Allows resources to be filtered by project.
	ProjectID *ProjectIDQueryParameter `form:"projectID,omitempty" json:"projectID,omitempty"`

	// RegionID Allows resources to be filtered by region.
	RegionID *RegionIDQueryParameter `form:"regionID,omitempty" json:"regionID,omitempty"`

	// NetworkID Allows resources to be filtered by network.
	NetworkID *NetworkIDQueryParameter `form:"networkID,omitempty" json:"networkID,omitempty"`
}

// GetApiV2InstancesInstanceIDConsoleoutputParams defines parameters for GetApiV2InstancesInstanceIDConsoleoutput.
type GetApiV2InstancesInstanceIDConsoleoutputParams struct {
	// Length The requested output length.
	Length *LengthParameter `form:"length,omitempty" json:"length,omitempty"`
}

// PostApiV2InstancesInstanceIDRebootParams defines parameters for PostApiV2InstancesInstanceIDReboot.
type PostApiV2InstancesInstanceIDRebootParams struct {
	// Hard Whether the reboot is hard.
	Hard *HardRebootParameter `form:"hard,omitempty" json:"hard,omitempty"`
}

// PostApiV2InstancesJSONRequestBody defines body for PostApiV2Instances for application/json ContentType.
type PostApiV2InstancesJSONRequestBody = InstanceCreate

// PutApiV2InstancesInstanceIDJSONRequestBody defines body for PutApiV2InstancesInstanceID for application/json ContentType.
type PutApiV2InstancesInstanceIDJSONRequestBody = InstanceUpdate

// PostApiV2InstancesInstanceIDSnapshotJSONRequestBody defines body for PostApiV2InstancesInstanceIDSnapshot for application/json ContentType.
type PostApiV2InstancesInstanceIDSnapshotJSONRequestBody = InstanceSnapshotCreate
