apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-server
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Orchestrate Unikorn resources (my job).
- apiGroups:
  - compute.unikorn-cloud.org
  resources:
  - computeclusters
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - delete
# Find project namespaces
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
