apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unikorn-compute-server
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Orchestrate Unikorn resources (my job).
- apiGroups:
  - compute.unikorn-cloud.org
  resources:
  - computeclusters
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - delete
- apiGroups:
  - compute.unikorn-cloud.org
  resources:
  - regions
  verbs:
  - list
  - watch
# Find project namespaces
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - list
  - watch
