apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-cluster-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Manage compute clusters (my job).
- apiGroups:
  - compute.unikorn-cloud.org
  resources:
  - computeclusters
  verbs:
  - list
  - watch
  - update
- apiGroups:
  - compute.unikorn-cloud.org
  resources:
  - computeclusters/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
# ArgoCD integration (access to API secret).
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
  - create
  - patch
  - delete
