apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unikorn-baremetal-cluster-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Manage baremetal clusters (my job).
- apiGroups:
  - baremetal.unikorn-cloud.org
  resources:
  - baremetalclusters
  verbs:
  - list
  - get
  - patch
  - watch
  - update
- apiGroups:
  - baremetal.unikorn-cloud.org
  resources:
  - baremetalclusters/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
