apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-monitor
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
rules:
# Manage kubernetes clusters and control planes (my job).
- apiGroups:
  - compute.unikorn-cloud.org
  resources:
  - computeclusters
  verbs:
  - list
  - watch
# Update status conditions
- apiGroups:
  - compute.unikorn-cloud.org
  resources:
  - computeclusters/status
  verbs:
  - patch
# Get region credentials.
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
